### ISSUE TITLE
Need some help in submitting wiki translation

### ISSUE THREAD

**Issue by Rad233** [melontini/andromeda-wiki#5]
Well, I'm the kind that needs very, very concrete examples, or I would mess up something. 
um, i mean, plz merge it yourself this time, i'm dumb
[andromeda-wiki-main.zip](https://github.com/melontini/andromeda-wiki/files/12642524/andromeda-wiki-main.zip)
```
  locales: {
    '/': {
      lang: 'zh_CN',
      title: '群星模组'
    },
    '/locale-path/': {
      lang: '2052', 
      title: '群星模组'
    }
  },
```
```
    locales: {
      '/': {
        selectLanguageName: '简体中文', 
      },
      '/locale-path/': {
        selectLanguageName: '简体中文',
        sidebar: [//wait, what links? 
        '/locale-path/README.md',
        '/locale-path/world/README.md',
        '/locale-path/blocks/README.md',
        '/locale-path/entities/README.md',
        '/locale-path/items/README.md',
        '/locale-path/bug-fixes/README.md',
        '/locale-path/mechanics/README.md',
        '/locale-path/gui/README.md',
        '/locale-path/misc/README.md',
    ],
      },
    },
```

**Comment by melontini** [comment]
Hi, thank you very much! I think it would be better to translate the `selectLanguageName` too.

**Comment by Rad233** [comment]
> Hi, thank you very much! I think it would be better to translate the `selectLanguageName` too.

done!

**Comment by melontini** [comment]
The translated wiki is now live over at https://andromeda-wiki.pages.dev/. Thanks again!
